# General Parameters
map_update_interval: 1.5  # Sedikit lebih cepat dari sebelumnya (1.5 detik)
maxUrange: 4.0           # Sesuaikan dengan range_max depthimage dikurangi sedikit
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 5
lsigma: 0.075
ogain: 3.0
lskip: 0
minimumScore: 100       # [PENTING] Naikkan skor minimum agar lebih yakin sebelum update peta

# Odometry Error Parameters
# Tingkatkan ini secara signifikan. Memberitahu GMapping untuk lebih percaya pada scan matching daripada odometry EKF
srr: 0.2
srt: 0.3
str: 0.2
stt: 0.3

# Update Thresholds
linearUpdate: 0.2     # Update setelah bergerak 20cm
angularUpdate: 0.17    # Update setelah berputar ~10 derajat
temporalUpdate: 0.5    # [PENTING] Paksa update setidaknya setiap 0.5 detik jika tidak ada gerakan besar

# Particle Filter Parameters
resampleThreshold: 0.5
particles: 80           # 80-100 cukup untuk area sedang-besar

# Initial Map Size
xmin: -30.0
ymin: -30.0
xmax: 30.0
ymax: 30.0

# Map Resolution
delta: 0.05             # 5cm per piksel

# Laser Likelihood Parameters
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005

# [PENTING] Parameter Tambahan untuk Stabilitas
# Seberapa jauh GMapping akan mencari kecocokan scan (meter). Perbesar sedikit.
maxRange: 5.0
# Seberapa besar perbedaan skor antara kecocokan terbaik dan kedua agar dianggap valid.
# Nilai lebih tinggi -> lebih selektif.
maxMatchScore: 0.2
# Penalti jika scan tidak cocok dengan peta. Menaikkan ini bisa mengurangi peta "bergeser".
map_match_threshold: 0.3
# Batasi seberapa jauh koreksi odometri dapat dilakukan dalam satu langkah (radian/meter).
# Ini bisa mencegah "lompatan" besar jika scan matching tiba-tiba menemukan kecocokan yang jauh.
max_correction_delta: 0.2
max_correction_delta_deg: 11.46 # Setara dengan 0.2 radian
