# --- Parameter Kunci yang Disesuaikan untuk Keseimbangan ---
maxUrange: 4.5
map_update_interval: 0.5
linearUpdate: 0.2
angularUpdate: 0.1
lskip: 2
particles: 150

# --- PERUBAHAN UTAMA UNTUK UPDATE SETIAP DETIK ---
temporalUpdate: 1.0        # DIUBAH: Paksa gmapping untuk memproses data baru setidaknya setiap 1.0 detik, meskipun robot tidak bergerak.

# --- Parameter Lainnya (biarkan seperti ini) ---
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 5
lsigma: 0.075
ogain: 3.0
minimumScore: 100
srr: 0.1
srt: 0.2
str: 0.1
stt: 0.2
resampleThreshold: 0.5
xmin: -15.0
ymin: -15.0
xmax: 15.0
ymax: 15.0
delta: 0.05
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
