<!--catkin_ws/src/autonomus_mobile_robot/config/gmapping_params.yaml-->
  # Konfigurasi GMapping yang Dioptimalkan untuk Pemetaan Lebih Cepat dan Detail
# Berdasarkan input dari Kinect yang sudah diperkaya datanya.

# Frame yang digunakan
base_frame: base_link
odom_frame: odom
map_frame: map

# ---- Parameter Kunci untuk Performa ----

# Seberapa sering peta diperbarui. Nilai lebih rendah = lebih sering update.
# Coba turunkan dari 5.0 ke 2.5 agar peta lebih cepat terbentuk.
map_update_interval: 2.5

# Jumlah partikel Monte Carlo. Ini adalah trade-off antara akurasi dan beban CPU.
# Dengan data laser yang lebih padat, kita tidak perlu partikel terlalu banyak.
# 40-80 adalah titik awal yang baik. Default-nya seringkali 30.
particles: 50

# ---- Kapan SLAM melakukan pembaruan ----
# Ini mencegah update yang terlalu sering jika robot hanya bergerak sedikit.
linearUpdate: 0.3  # Update jika robot bergerak maju/mundur sejauh 30 cm
angularUpdate: 0.2 # Update jika robot berputar sejauh 0.2 radian (~11.5 derajat)

# ---- Parameter Sensor Laser ----
# Jarak maksimum dari sensor yang akan diproses. Sesuaikan jika perlu.
maxUrange: 8.0
maxRange: 10.0

# ---- Parameter Internal GMapping (umumnya tidak perlu diubah) ----
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 5
lsigma: 0.075
ogain: 3.0
lskip: 0
srr: 0.1
srt: 0.2
str: 0.1
stt: 0.2
temporalUpdate: -1.0 # -1.0 berarti update hanya berdasarkan gerakan (linear/angularUpdate)
resampleThreshold: 0.5
xmin: -15.0 # Perluas sedikit ukuran awal peta
ymin: -15.0
xmax: 15.0
ymax: 15.0
delta: 0.05 # Resolusi peta (5 cm per sel), ini sudah standar dan baik
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
